---
title: "lasso"
author: "Junjie Hu"
date: "2023-12-07"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(glmnet)

set.seed(11)

```

```{r}
bwt_df = 
  read_csv("data/birthweight.csv") |> 
  janitor::clean_names() |>
  mutate(
    babysex = as.factor(babysex),
    babysex = fct_recode(babysex, "male" = "1", "female" = "2"),
    frace = as.factor(frace),
    frace = fct_recode(
      frace, "white" = "1", "black" = "2", "asian" = "3", 
      "puerto rican" = "4", "other" = "8"),
    malform = as.logical(malform),
    mrace = as.factor(mrace),
    mrace = fct_recode(
      mrace, "white" = "1", "black" = "2", "asian" = "3", 
      "puerto rican" = "4")) |> 
  sample_n(200)
```

get predictors and outcome.
```{r}
x = model.matrix(bwt ~ ., bwt_df)[, -1]
y = bwt_df |> pull(bwt)

```

```{r}
lambda = 10^(seq(3, -2, -0.1))

lasso_fit =
  glmnet(x, y, lambda = lambda)

lasso_cv =
  cv.glmnet(x, y, lambda = lambda)

lambda_opt = lasso_cv$lambda.min
```

Let's look at lasso results!

```{r}

lasso_fit |> 
  broom::tidy() |> 
  select(term, lambda, estimate) |> 
  complete(term, lambda, fill = list(estimate = 0) ) |> 
  filter(term != "(Intercept)") |> 
  ggplot(aes(x = log(lambda, 10), y = estimate, group = term, color = term)) + 
  geom_path()


```

Show the CV results

```{r}
lasso_cv |>
  broom::tidy() |>
  ggplot(aes(x = log(lambda, 10), y = estimate)) +
  geom_point()
```

## Penguins

```{r}
library(palmerpenguins)

data("penguins")

penguins = 
  penguins |> 
  select(species, bill_length_mm, flipper_length_mm) |> 
  drop_na() 

penguins |> 
  ggplot(aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + 
  geom_point()

```

```{r}
kmeans_fit =
  penguins |>
  select(-species) |>
  kmeans(centers = 3)

penguins |>
  broom::augment(kmeans_fit, data = _) |>
  ggplot(aes(x = bill_length_mm, y = flipper_length_mm, color = .cluster)) +
  geom_point()

```

## trajectories

```{r}
traj_data = 
  read_csv("./data/trajectories.csv")

traj_data |> 
  ggplot(aes(x = week, y = value, group = subj)) + 
  geom_point() + 
  geom_path()

int_slope_df = 
  traj_data |> 
  nest(data = week:value) |> 
  mutate(
    models = map(data, \(df) lm(value ~ week, data = df)),
    result = map(models, broom::tidy)
  ) |> 
  select(subj, result) |> 
  unnest(result) |> 
  select(subj, term, estimate) |> 
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) |> 
  rename(int = "(Intercept)", slope = week)
```

